version: '3'
services:
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid:latest-release
    volumes:
      - "./selenoid:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./selenoid/video:/opt/selenoid/video"
      - "./selenoid/logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/path/to/config/video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]
    ports:
      - "${SELENIUM_PORT}:4444"

  selenoid-ui:
    network_mode: bridge
    image: aerokube/selenoid-ui:latest-release
    links:
      - selenoid
    ports:
      - "${SELENOID_UI_PORT}:8080"
    command: ["--selenoid-uri", "http://${SELENIUM_HOST}:${SELENIUM_PORT}"]
  testing:
    network_mode: host
    image: computer-database-ui-tests
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./report:/var/report
    command: ["pytest", "-s", "--base_url=${base_url}", "--dashboard", "--html=/var/report/dashboard.html", "--self-contained-html", "-l", "-v", "-n=${parallel}", "--server=${SELENIUM_HOST}", "--port=${SELENIUM_PORT}", "--cap_file=cap.py", "--headed", "--maximize-window", "-k ${run}"]
